### PR TITLE
Fix out-of-tree builds

### PR DESCRIPTION
**Pull request by rpavlik**
The CMake script is not super idiomatic: it wouldn't work at all with an out of tree build which is best practice. I cleaned it up a little bit so that

### CODE REVIEW

**Comment by rajaramINTC** [comment]
Could you also pls help fix lstypec.c "#include "../libtypec.h" ? This would make the pull complete

**Comment by Rajaram-Regupathy** [comment]
Could you also pls help fix lstypec.c "#include "../libtypec.h" ? This would make the pull complete

**Comment by rpavlik** [comment]
Yeah I have a finished thing here, I was trying to make sure it actually ran first.

**Comment by rpavlik** [comment]
OK, I pushed the full thing. I still didn't get it to run successfully here but that might just be my system. It does build just fine.

Note that I did add one more commit to make the CMake build better/more idiomatic.

**Comment by rpavlik** [comment]
OK, I tested this on my laptop (xps 13 9370, debian bookworm), works nicely

**Pull request merged**
